[package]
name = "axum_static_macro"
version = "1.0.1"
edition = "2021"
description = "A macro to serve static files from the binary in Axum"
license = "MIT OR Apache-2.0"
repository = "https://github.com/randomairborne/axum_static_macro"
keywords = ["axum", "macro", "static_files"]
categories = ["web-programming"]


[dependencies]
http = "0.2"
tracing = "0.1"